shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('www.urls')),
]

www/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('search/', views.search, name='search'),
    path('product/', views.product, name='product'),
    path('cart/', views.cart, name='cart'),
    path('discounts/', views.discounts, name='discounts'),
    path('steamWallet/', views.steamWallet, name='steamWallet'),
    path('feedback/', views.feedback, name='feedback'),
    path('privacyPolicy/', views.privacyPolicy, name='privacyPolicy'),
    path('agreement/', views.agreement, name='agreement'),
    path('contacts/', views.contacts, name='contacts'),
    path('payment/', views.payment, name='payment'),
    path('order/', views.order, name='order'),
]

www/models.py
from django.db import models


class Feedback(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(max_length=255)
    message = models.TextField()
    created_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'feedback'


class Genres(models.Model):
    genre_id = models.AutoField(primary_key=True)
    genre_name = models.CharField(unique=True, max_length=100)

    class Meta:
        managed = False
        db_table = 'genres'


class Platforms(models.Model):
    platform_id = models.AutoField(primary_key=True)
    platform_name = models.CharField(unique=True, max_length=100)

    class Meta:
        managed = False
        db_table = 'platforms'


class ProductGenres(models.Model):
    pk = models.CompositePrimaryKey('product_id', 'genre_id')
    product = models.ForeignKey('Products', models.DO_NOTHING)
    genre = models.ForeignKey(Genres, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'product_genres'


class ProductPlatforms(models.Model):
    pk = models.CompositePrimaryKey('product_id', 'platform_id')
    product = models.ForeignKey('Products', models.DO_NOTHING)
    platform = models.ForeignKey(Platforms, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'product_platforms'


class Products(models.Model):
    id = models.CharField(primary_key=True, max_length=255)
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image_url = models.CharField(max_length=255, blank=True, null=True)
    old_price = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True)
    discount_percent = models.IntegerField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    # This field type is a guess.
    action_tags = models.TextField(blank=True, null=True)
    # This field type is a guess.
    screenshot_urls = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'products'


class Screenshots(models.Model):
    screenshot_id = models.AutoField(primary_key=True)
    product = models.ForeignKey(
        Products, models.DO_NOTHING, blank=True, null=True)
    image_url = models.CharField(max_length=255)
    display_order = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'screenshots'


class PopularProducts(models.Model):
    product = models.OneToOneField('Products', models.DO_NOTHING, primary_key=True)

    class Meta:
        managed = False
        db_table = 'popular_products'

www/views.py
from django.shortcuts import render, get_object_or_404
from .models import Products, Genres, Platforms, ProductGenres, ProductPlatforms, PopularProducts
from django.db.models import Q

def index(request):
    popular_products_links = PopularProducts.objects.select_related('product').prefetch_related(
            'product__productgenres_set__genre',
            'product__productplatforms_set__platform'
        ).all()

    popular_products = [pp.product for pp in popular_products_links]
    context = {
        'popular_products': popular_products,
    }
    return render(request, 'index.html', context)


def search(request):
    query = request.GET.get('q', '')
    genre_id = request.GET.get('genre')
    platform_id = request.GET.get('platform')
    sort_order = request.GET.get('sort')

    # products = Products.objects.all()
    products = Products.objects.all().prefetch_related('productplatforms_set__platform')

    if query:
        products = products.filter(
            Q(name__icontains=query) | Q(action_tags__icontains=query)
        )

    if genre_id:
        products = products.filter(productgenres__genre_id=genre_id)

    if platform_id:
        products = products.filter(productplatforms__platform_id=platform_id)

    if sort_order == 'price_asc':
        products = products.order_by('price')
    elif sort_order == 'price_desc':
        products = products.order_by('-price')

    genres = Genres.objects.all()
    platforms = Platforms.objects.all()

    return render(request, 'search.html', {
        'products': products,
        'genres': genres,
        'platforms': platforms,
    })


def product(request):
    product_id = request.GET.get('id')
    product = get_object_or_404(Products, pk=product_id)

    # жанры и платформы
    genres = ProductGenres.objects.filter(product=product).select_related('genre')
    platforms = ProductPlatforms.objects.filter(product=product).select_related('platform')

    # обработка screenshot_urls
    raw_screens = product.screenshot_urls

    if isinstance(raw_screens, str):
        screenshots = [img.strip() for img in raw_screens.split(',') if img.strip()]
    elif isinstance(raw_screens, list):
        screenshots = raw_screens
    else:
        screenshots = []

    context = {
        'product': product,
        'genres': [g.genre.genre_name for g in genres],
        'platforms': [p.platform.platform_name for p in platforms],
        'screenshots': screenshots,
    }

    return render(request, 'product.html', context)


def cart(request):
    return render(request, 'cart.html')


def discounts(request):
    query = request.GET.get('q', '')

    products = Products.objects.filter(discount_percent__gt=0)

    if query:
        products = products.filter(
            Q(name__icontains=query) | Q(action_tags__icontains=query)
        )

    return render(request, 'discounts.html', {
        'products': products,
    })


def steamWallet(request):
    return render(request, 'steamWallet.html')


def feedback(request):
    return render(request, 'feedback.html')


def privacyPolicy(request):
    return render(request, 'privacyPolicy.html')


def agreement(request):
    return render(request, 'agreement.html')


def contacts(request):
    return render(request, 'contacts.html')


def payment(request):
    return render(request, 'payment.html')


def order(request):
    return render(request, 'order.html')

www/templates/agreement.html
{% extends "base.html" %}
{% load static %}

{% block title %}Пользовательское соглашение {% endblock %}
{% block style %}{% static 'css/privacyPolicy.css' %}{% endblock %}

{% block content %}
<main>
    <h1>Пользовательское соглашение (Публичная оферта)</h1>
    <nav class="breadcrumbs">
        <ol>
            <li><a href="{% url 'home' %}">Главная</a></li>
            <li><span>Пользовательское соглашение</span></li>
        </ol>
    </nav>
    <pre>
Настоящий документ является официальным предложением (офертой) ООО «Game Dealers» в адрес любого дееспособного лица (далее — «Пользователь») заключить договор на условиях, изложенных ниже.

1. Предмет соглашения
Мы предоставляем цифровые товары и услуги (ключи, подписки, пополнение аккаунтов, и др.) через интернет-сайт gamedealers.ru.

2. Оформление заказа
Пользователь оформляет заказ через интерфейс сайта. С момента оплаты договор считается заключённым. Заказ считается выполненным после доставки товара (в виде цифрового кода, активации, отправки).

3. Цены и оплата
Все цены указаны в российских рублях. Оплата возможна с использованием электронных платёжных систем, банковских карт и других доступных способов.

4. Возврат и отказ
Цифровые товары не подлежат возврату после предоставления, согласно п.14 Правил дистанционной торговли. В случае технической ошибки или невозможности оказания услуги — возможен возврат средств.

5. Ответственность сторон
Мы не несем ответственности за:
— неправильно указанные данные Пользователем;
— технические сбои сторонних сервисов;
— использование данных, нарушающих правила Steam или других платформ.

6. Персональные данные
Пользователь соглашается с Политикой конфиденциальности, размещённой на сайте.

7. Заключительные положения
Настоящее соглашение может быть изменено без предварительного уведомления. Актуальная версия доступна на сайте.

Дата публикации оферты: 12 июня 2025 г.
    </pre>

</main>
{% endblock %}
{% block extra_scripts %}
<script src="{% static 'js/cartCounter.js' %}"></script>
{% endblock %}

www/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}GameDealers — the best stuff{% endblock %}</title>
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="{% block style %}{% static 'css/index.css' %}{% endblock %}" rel="stylesheet">

    <link href="{% static 'images/icons/Gicon.svg' %}" rel="icon" type="image/x-icon">
</head>
<body>
    <div class="wrapper">
        <div class="content">
            <header>
                <div class="logo">
                    <a href="{% url 'home' %}">
                        <img src="{% static 'images/Logo.png' %}" alt="GameDealers logo" title="The Best Stuff">
                    </a>
                </div>
                <nav class="header-menu">
                    <div class="header-menu-icon">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                    <div class="header-menu-body">
                        <ul class="header-menu-list">
                            <li><a href="{% url 'home' %}" class="link to-home">На главную</a></li>
                            <li><a href="{% url 'discounts' %}" class="link">Акции&nbsp;🔥</a></li>
                            <li><a href="{% url 'steamWallet' %}" class="link">Пополнение&nbsp;Steam</a></li>
                            <li><a href="#" class="link">Консоли</a></li>
                            <li><a href="#" class="link">Программы</a></li>
                            <li><a href="#" class="link">Предметы&nbsp;для&nbsp;игр</a></li>
                            <li><a href="#" class="link">Подписки</a></li>
                        </ul>
                    </div>
                </nav>
                <div class="buttons-container">
                    <a href="{% url 'search' %}" title="Поиск по всем товарам">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd"
                                d="M9.10932 18.2186C14.1403 18.2186 18.2186 14.1402 18.2186 9.10931C18.2186 4.07838 14.1403 0 9.10932 0C4.07834 0 0 4.07838 0 9.10931C0 14.1402 4.07834 18.2186 9.10932 18.2186ZM9.10932 16.0752C12.9565 16.0752 16.0753 12.9565 16.0753 9.10931C16.0753 5.26212 12.9565 2.14337 9.10932 2.14337C5.26214 2.14337 2.14337 5.26212 2.14337 9.10931C2.14337 12.9565 5.26214 16.0752 9.10932 16.0752Z" />
                            <path d="M15.4475 13.9319L24 22.4844L22.4844 24L13.9319 15.4475L15.4475 13.9319Z" />
                        </svg>
                    </a>
                    <!-- <a href="#" title="Личный кабинет">
                        <svg width="15" height="24" viewBox="0 0 15 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M7.5 9.28132C4.98992 9.28132 2.93347 7.19149 2.93347 4.64066C2.96371 2.08983 4.98992 0 7.5 0C10.0101 0 12.0665 2.08983 12.0665 4.64066C12.0665 7.19149 10.0403 9.28132 7.5 9.28132ZM7.5 2.08983C6.10887 2.08983 4.98992 3.22695 4.98992 4.64066C4.98992 6.05437 6.10887 7.19149 7.5 7.19149C8.89113 7.19149 10.0101 6.05437 10.0101 4.64066C10.0101 3.22695 8.89113 2.08983 7.5 2.08983Z" />
                            <path
                                d="M12.9738 24V18.2553C12.9738 15.182 10.5242 12.7234 7.53024 12.7234C4.50605 12.7234 2.08669 15.2128 2.08669 18.2553V24H0V18.2553C0 14.0449 3.35685 10.6336 7.5 10.6336C11.6431 10.6336 15 14.0449 15 18.2553V24H12.9738Z" />
                        </svg>
                    </a> -->
                    <a href="{% url 'cart' %}" title="Корзина" class="cart-icon">
                        <svg width="27" height="25" viewBox="0 0 27 25" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M4.44457 25L1.6327 13.8197H0V7.50297H6.22844L9.2822 0L11.0358 0.682088L8.2542 7.53262H18.6853L15.9339 0.682088L17.6876 0L20.7413 7.50297H26.9698V13.8197H25.3371L22.5252 25H4.44457ZM21.0739 23.1613L23.4323 13.8493H3.56775L5.92609 23.1613H21.0739ZM25.0952 11.981V9.40095H1.90482V11.981H25.0952Z" />
                            <path d="M14.4523 15.3914H12.5475V22.064H14.4523V15.3914Z" />
                            <path d="M18.0806 15.3914H16.1758V22.064H18.0806V15.3914Z" />
                            <path d="M10.8242 15.3914H8.91936V22.064H10.8242V15.3914Z" />
                        </svg>
                        <span class="cart-count" id="cart-count">0</span>
                    </a>
                </div>
            </header>

            {% block content %}
            <!-- <main>
                
            </main> -->
            {% endblock %}
            
        </div>

        <footer class="footer">
            <div class="footer-inner">
                <div class="footer-upper-block">
                    <div class="footer-logo">
                        <a href="{% url 'home' %}">
                            <img src="{% static 'images/Logo.png' %}" alt="GameDealers logo" title="The Best Stuff">
                        </a>
                    </div>
                    <div class="footer-upper-block-links">
                        <div class="footer-upper-block-links-container">
                            <a href="{% url 'feedback' %}">Обратная связь</a>
                            <!-- <a href="#">Отзывы</a> -->
                            <a href="{% url 'payment' %}">Способы оплаты</a>
                            <a href="{% url 'contacts' %}">Контакты</a>
                        </div>
                        <div class="discord">
                            <p>Загляни&nbsp;в&nbsp;наш&nbsp;дискорд</p>
                            <a class="discord-link" href="#">discord.com/g0med1las</a>
                        </div>
                    </div>
                </div>

                <hr class="footer-divider">

                <div class="footer-lower-block">
                    <p>&copy;2025, ООО &#171;Game Dealers&#187;, официальный сайт</p>
                    <div class="footer-lower-block-links">
                        <a href="{% url 'privacyPolicy' %}">Политика конфиденциальности и оферта</a>
                        <a href="{% url 'agreement' %}">Пользовательское соглашение</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    {% block modals %}{% endblock %}

    <script src="{% static 'js/burgerMenu.js' %}"></script>

    {% block extra_scripts %}{% endblock %}
</body>
</html>

www/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}GameDealers — the best stuff{% endblock %}
{% block style %}{% static 'css/index.css' %}{% endblock %}

{% block content %}
<main class="main">
    <section class="intro-section">
        <div class="intro-content">
            <p class="intro-text">
                Пополнение Steam, подписки, программы и многое другое!
            </p>
            <div class="dotted-rectangle"></div>
            <div class="discord">
                <p>Загляни в наш дискорд</p>
                <a class="discord-link" href="#">discord.com/g0med1las</a>
            </div>

            
            <div class="main-action">
                <h2>Акция недели!</h2>
                <a href="{% url 'product' %}?id=4">
                    <div class="action-game-image"></div>
                </a>
                <a href="{% url 'product' %}?id=4" class="game-name">
                    <p>Red Dead Redemption 2</p>
                </a>
                <div class="old-price-container">
                    <span class="old-price">5999&nbsp;&#8381;</span>
                    <span class="discount">-67%</span>
                </div>
                <div class="price-cart">
                    <span class="price">1980&nbsp;&#8381;</span>
                    <div class="card-button add-to-cart-button" 
                        data-product-id="4" 
                        data-product-name="Red Dead Redemption 2" 
                        data-product-price="1980,00" 
                        data-product-image="Red_Dead_Redemption_2_coverart.jpg" 
                        data-product-platforms="1:Steam;7:PlayStation 4;2:PlayStation 5;3:Xbox">
                    </div>
                </div>
            </div>
        </div>

       
        <div class="main-banner">
            <div class="dotted-rectangle-2"></div>
            <h2>Новинка!</h2>
            <div class="main-banner-offer">
                <div class="main-banner-offer-inner">
                    <a class="main-banner-link" href="{% url 'product' %}?id=29">
                        <h3>DELTARUNE</h3>
                    </a>
                    <p>Захватывающая JRPG от Тоби Фокса, создателя знаменитой Undertale. 
                        Погрузитесь в уникальное приключение, полное отличного юмора, 
                        незабываемых персонажей и сюрреалистического мира</p>
                    <div class="price-cart">
                        <span class="price">1099&nbsp;&#8381;</span>
                        <div class="card-button add-to-cart-button" 
                            data-product-id="29" data-product-name="DELTARUNE" 
                            data-product-price="1099,00" 
                            data-product-image="Deltarune.jpg" 
                            data-product-platforms="1:Steam">
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="catalog">
        <h1>Популярные преложения</h1>
        <div class="catalog-grid-container">
            {% for product in popular_products %}
            <div class="product-card">
                <div class="game-image">
                    <a href="{% url 'product' %}?id={{ product.id }}">
                        {% if product.image_url %}
                        <img src="{% static 'images/' %}{{ product.image_url }}" alt="{{ product.name }}">
                        {% else %}
                        <div class="no-image">Нет изображения</div>
                        {% endif %}
                    </a>    
                </div>
                <a href="{% url 'product' %}?id={{ product.id }}">
                    <p class="game-name">{{ product.name|default:'Без названия' }}</p>
                </a>
                {% if product.discount_percent %}
                <div class="old-price-container">
                    <span class="old-price">{{ product.old_price|floatformat:2 }}&nbsp;&#8381;</span>
                    <span class="discount">-{{ product.discount_percent }}%</span>
                </div>
                {% endif %}
                <div class="price-cart">
                    <span class="price">{{ product.price|floatformat:2 }}&nbsp;&#8381;</span>
                    <div class="card-button add-to-cart-button" data-product-id="{{ product.id }}"
                        data-product-name="{{ product.name }}" data-product-price="{{ product.price|floatformat:2 }}"
                        data-product-image="{{ product.image_url|default:'No-img.png' }}"
                        data-product-platforms="{% for pp in product.productplatforms_set.all %}{{ pp.platform.platform_id }}:{{ pp.platform.platform_name }}{% if not forloop.last %};{% endif %}{% endfor %}">
                    </div>
                </div>
            </div>
            {% empty %}
            <p>Нет популярных предложений.</p>
            {% endfor %}

            <div class="product-card">
                <div class="game-image">
                    <a href="{% url 'steamWallet' %}">
                        <img src="{% static 'images/steam.jpg' %}" alt="Steam Wallet">
                    </a>
                </div>
                <a href="{% url 'steamWallet' %}">
                    <p class="game-name">Steam Wallet</p>
                </a>
                <div class="price-cart">
                    <span class="price">От&nbsp;100&nbsp;&#8381;</span>
                    <a href="{% url 'steamWallet' %}">
                        <div class="card-button"></div>
                    </a>
                </div>
            </div>

        </div>
        <a href="{% url 'search' %}">
            <div class="all-products-link">
                <span>Ко всем товарам</span>
            </div>
        </a>
    </section>

    <section class="categories">
        <div class="categories-head">
            <h1>Категории</h1>
            <div class="slider-buttons">
                <button class="slider-button prev" type="button">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
                        <path d="M15.41 16.59L10.83 12l4.58-4.59L14 6l-6 6 6 6 1.41-1.41z" fill="white" />
                    </svg>
                </button>
                <button class="slider-button next" type="button">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
                        <path d="M8.59 16.59L13.17 12 8.59 7.41 10 6l6 6-6 6-1.41-1.41z" fill="white" />
                    </svg>
                </button>
            </div>
        </div>
        <div class="categories-grid-container">
            <a href="{% url 'discounts' %}">
                <div class="categories-grid-container-item red-background">
                    <div class="discount-label">
                        <img src="{% static 'images/icons/thirty.svg' %}" class="number">
                        <img src="{% static 'images/icons/percent.svg' %}" class="percent">
                    </div>
                    <span>Акции&nbsp;🔥</span>
                    <div class="discount-label">
                        <img src="{% static 'images/icons/twenty.svg' %}" class="number">
                        <img src="{% static 'images/icons/percent.svg' %}" class="percent">
                    </div>
                </div>
            </a>
            <a href="{% url 'steamWallet' %}">
                <div class="categories-grid-container-item repeat-back">
                    <span>Пополнение Steam</span>
                    <img src="{% static 'images/steam-back.png' %}">
                </div>
            </a>
            <a href="#">
                <div class="categories-grid-container-item repeat-back">
                    <span>Игровые ключи и активации</span>
                    <img src="{% static 'images/keys-back.png' %}">
                </div>
            </a>
            <a href="#">
                <div class="categories-grid-container-item repeat-back">
                    <span>Игры для консолей</span>
                    <img src="{% static 'images/Console-back.png' %}">
                </div>
            </a>
            <a href="#">
                <div class="categories-grid-container-item repeat-back">
                    <span>Подарочные карты</span>
                    <img src="{% static 'images/gift-back.png' %}">
                </div>
            </a>
            <a href="#">
                <div class="categories-grid-container-item repeat-back">
                    <span>Программное обеспечение</span>
                    <img src="{% static 'images/software-back.png' %}">
                </div>
            </a>
            <a href="#">
                <div class="categories-grid-container-item repeat-back">
                    <span>Виртуальная реальность (VR)</span>
                    <img src="{% static 'images/vr-back.png' %}">
                </div>
            </a>
            <a href="#">
                <div class="categories-grid-container-item repeat-back repeat-back">
                    <span>Игровые предметы и внутриигровая валюта</span>
                    <img src="{% static 'images/game-items.png' %}">
                </div>
            </a>
            <a href="#">
                <div class="categories-grid-container-item repeat-back">
                    <span>Подписки на сервисы</span>
                    <img src="{% static 'images/subscriptions-services.png' %}">
                </div>
            </a>

            <a href="#">
                <div class="categories-grid-container-item repeat-back">
                    <span>Облачные игры</span>
                    <img src="{% static 'images/cloud-games.png' %}">
                </div>
            </a>

        </div>
    </section>
</main>
{% endblock %}

{% block modals %}
<div id="quickAddToCartModal" class="modal">
    <div class="modal-content">
        <div class="modal-product-image">
            <img id="modalProductImage" src="" alt="Product Image">
        </div>
        <div class="info-container">
            <h2 id="modalProductName"></h2>
            <p class="modal-product-price">Цена: <strong><span id="modalProductPrice"></span>&nbsp;₽</strong></p>
            <div class="modal-platforms-container">
                <p>Выберите платформу:</p>
                <div id="modal-platforms" class="modal-platforms"></div>
            </div>
            <button id="modalAddToCartButton" class="buy-button">Добавить в корзину</button>
        </div>
        <span class="close-button">&times;</span>
    </div>
</div>
{% endblock %}

{% block extra_scripts %}
<script src="{% static 'js/categoriesScroller.js' %}"></script>
<script src="{% static 'js/cartCounter.js' %}"></script>
<script src="{% static 'js/quickAddToCart.js' %}"></script>
{% endblock %}

www/templates/search.html
{% extends "base.html" %}
{% load static %}

{% block title %}GameDealers — Поиск{% endblock %}
{% block style %}{% static 'css/search.css' %}{% endblock %}

{% block content %}
<main class="main">
    <div class="search-head">

        <form method="get" class="search-form">
            <h1>Все товары</h1>
            <nav class="breadcrumbs">
                <ol>
                    <li><a href="{% url 'home' %}">Главная</a></li>
                    <li><span>Все товары</span></li>
                </ol>
            </nav>
            <input type="text" name="q" class="search-form-input" placeholder="Введите название или тег..."
                value="{{ request.GET.q }}">

            <div class="select-container">
                <select name="genre" class="search-form-select">
                    <option value>Все жанры</option>
                    {% for genre in genres %}
                    <option value="{{ genre.genre_id }}" {% if genre.genre_id|stringformat:"s" == request.GET.genre%}selected{% endif %}>{{genre.genre_name }}
                    </option>
                    {% endfor %}
                </select>

                <select name="platform" class="search-form-select">
                    <option value>Все платформы</option>
                    {% for platform in platforms %}
                    <option value="{{ platform.platform_id }}" {% if platform.platform_id|stringformat:"s" == request.GET.platform %}selected{% endif %}>{{platform.platform_name }}</option>
                    {% endfor %}
                </select>

                <select name="sort" class="search-form-select">
                    <option value>Сортировать</option>
                    <option value="price_asc" {% if request.GET.sort == "price_asc" %}selected{% endif %}>
                        Цена по возрастанию
                    </option>
                    <option value="price_desc" {% if request.GET.sor == "price_desc" %}selected{% endif %}>
                        Цена по убыванию
                    </option>
                </select>
            </div>

            <button type="submit">Найти</button>
        </form>

    </div>
    {% if products %}
    <div class="catalog-grid-container">
        {% for product in products %}
        <div class="product-card">
            <div class="game-image">
                <a href="{% url 'product' %}?id={{ product.id }}">
                    {% if product.image_url %}
                    <img src="/static/images/{{ product.image_url }}" alt="{{ product.name }}">
                    {% else %}
                    <div class="no-image">Нет изображения</div>
                    {% endif %}
                </a>
            </div>
            <a href="{% url 'product' %}?id={{ product.id }}">
                <p class="game-name">
                    {{ product.name|default:'Без названия' }}
                </p>
            </a>
            {% if product.discount_percent %}
            <div class="old-price-container">
                <span class="old-price">
                    {{ product.old_price|floatformat:2}}&nbsp;₽
                </span>
                <span class="discount">
                    -{{ product.discount_percent }}%
                </span>
            </div>
            {% endif %}
            <div class="price-cart">
                <span class="price">
                    {{ product.price|floatformat:2 }}&nbsp;₽
                </span>
                <div class="card-button add-to-cart-button" data-product-id="{{ product.id }}"
                    data-product-name="{{ product.name }}" data-product-price="{{ product.price|floatformat:2 }}"
                    data-product-image="{{ product.image_url|default:'No-img.png' }}"
                    data-product-platforms="{% for pp in product.productplatforms_set.all %}{{ pp.platform.platform_id }}:{{ pp.platform.platform_name }}{% if not forloop.last %};{% endif %}{% endfor %}">
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p class="empty-result-message">
        По вашему запросу товаров не найдено.
    </p>
    {% endif %}
</main>
{% endblock %}
{% block modals %}
<div id="quickAddToCartModal" class="modal">
    <div class="modal-content">
        <div class="modal-product-image">
            <img id="modalProductImage" src="" alt="Product Image">
        </div>
        <div class="info-container">
            <h2 id="modalProductName"></h2>
            <p class="modal-product-price">Цена: <strong><span id="modalProductPrice"></span>&nbsp;₽</strong></p>
            <div class="modal-platforms-container">
                <p>Выберите платформу:</p>
                <div id="modal-platforms" class="modal-platforms"></div>
            </div>
            <button id="modalAddToCartButton" class="buy-button">Добавить в корзину</button>
        </div>
        <span class="close-button">&times;</span>
    </div>
</div>
{% endblock %}
{% block extra_scripts %}
<script src="{% static 'js/cartCounter.js' %}"></script>
<script src="{% static 'js/quickAddToCart.js' %}"></script>
{% endblock %}